MY-PROJECT/common/urls.py
from django.urls import path
from.import views
app_name = 'common'

urlpatterns=[
    path('admin_logo',views.admin_logo),
    path('customer_login',views.customer_login,name='clogin'),
    path('customer_signup',views.customer_signup,name='csign'),
    path('home',views.home,name='home'),
    path('seller_login',views.seller_login,name='slogin'),
    path('seller_signup',views.seller_signup,name='ssign'),
]

MY-PROJECT/customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('change_password',views.change_password,name='password'),
    path('checkout',views.checkout,name='check'),
    path('home',views.home,name='home'),
    path('myorders',views.myorders,name='orders'), 
    path('productdetails/<int:pid>',views.productdetails,name='details'), 
    path('profile',views.profile,name='profile'),
    path('mycart',views.mycart,name='cart'),
    path('get_total_amount',views.get_total_price,name='total_price'),
    path('remove_cart/<int:cid>',views.remove_cart_item,name='remove_cart'),
    path('logout',views.logout,name='logout'),
]

MY-PROJECT/ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('common/',include('common.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

MY-PROJECT/customer/models.py
from django.db import models
from common.models import Customer
from seller.models import Product


# Create your models here.

class Cart(models.Model):
    
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    class Meta:
        db_table = 'cart_tb'

MY-PROJECT/customer/views.py
from django.shortcuts import render,redirect
from common.models import Customer
from seller.models import Product
from .models import Cart
from django.http import JsonResponse
from. decorater  import auth_customer



# Create your views here.
@auth_customer
def change_password(request):
    error_msg = ''
    success_msg = ''
    if request.method == 'POST':
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        if new_password == confirm_password:
            if len(new_password) > 8:
                customer = Customer.objects.get(id = request.session['customer'])
                if old_password == customer.password:
                    Customer.objects.filter(id = request.session['customer']).update(password = new_password)
                   
                    success_msg = 'updated successfully'
                else:
                    error_msg = 'Invalid password'    

            else:
                error_msg = 'Password should be minimum 8 characters'
        
        else :
            error_msg = 'password does\'nt  match'
    



    return render(request,'customer/change password.html',{'success':success_msg,'error':error_msg})


def checkout(request):
    return render(request,'customer/checkout.html')

@auth_customer
def home(request):
    customer_details = Customer.objects.get(id = request.session['customer'])
    products = Product.objects.all()
    cname = customer_details.first_name + ' ' + customer_details.last_name
    context = {
        'name':cname,
        'products':products

    }
    return render(request,'customer/home.html',context)    

def myorders(request):
    return render(request,'customer/myorders.html')  

@auth_customer
def productdetails(request,pid):
    product_details = Product.objects.get(id = pid)
    msg = ''
    if request.method == 'POST':
        item = Cart.objects.filter(customer = request.session['customer'],product = pid).exists()
        if not item:           #same as if item == false:

            cart_item = Cart(customer_id = request.session['customer'],product_id = pid)
            cart_item.save()
            return redirect('customer:cart')
        else:
            msg = 'Item already in cart'


    return render(request,'customer/productdetails.html',{'details':product_details,'message':msg})
    

def profile(request):
    return render(request,'customer/profile.html')  

@auth_customer
def mycart(request): 
    items = Cart.objects.filter(customer_id = request.session['customer'])
    return render(request,'customer/mycart.html',{'items':items})

    
  
def get_total_price(request):
    pid = request.POST['pid']    #pid is the key passed from ajax request
    qty = request.POST['qty']
    product = Product.objects.filter(id = pid).values('price')
    total_amount = int(qty) * product[0]['price']
    print(total_amount)
    return JsonResponse({'amount': total_amount})

def remove_cart_item(request,cid):
    item = Cart.objects.get(id = cid)
    item.delete()
    return redirect('customer:cart')


def logout(request):
    del request.session['customer']
    request.session.flush()
    return redirect('common:home')

MY-PROJECT/customer/templates/customer/change password.html
{% extends "customer/master.html" %}
{% load static %}
{% block link %}<link rel="stylesheet" href="{% static 'styles/form.css' %}">
<link rel="stylesheet" href="{% static 'styles/change_password.css' %}">
    
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css"> {% endblock %}
{% block content %}


   
    <div  class="position-absolute top-50 start-50 translate-middle form">
        <div class="modal-header">
          
            <h1 class="modal-title fs-7 mb-3 text-danger" id="exampleModalToggleLabel">Change Password</h1>
            
          </div>
    
      <form method="POST"  class="form1">
        {% csrf_token %}
        
        <div class="mb-3 ">
          <label for="exampleInputPassword1" class="form-label text-white">Old Password</label>
          <input type="password" class="form-control" name="old_password" id="exampleInputPassword1">
        </div>
        <div class="mb-3 ">
            <label for="exampleInputPassword1" class="form-label text-white">New Password</label>
            <input type="password" class="form-control" name="new_password" id="exampleInputPassword1">
          </div>
          <div class="mb-3 ">
            <label for="exampleInputPassword1" class="form-label text-white">Confirm Password</label>
            <input type="password" class="form-control" name="confirm_password" id="exampleInputPassword1">
          </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
        {{success}} {{error}}
      </form>
    </div>
</div>


  <!-- FOOTER START-->
  <!-- <div class="card text-center bg-dark">
    <div class="card-footer text-muted">
      2022 ECOM Inc,  All Rights Reserved. 
    </div>
  </div> -->
  <!--FOOTER END -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  


{% endblock %}

MY-PROJECT/customer/templates/customer/home.html
{% extends "customer/master.html" %}
{% load static %}
{% block content %}

  <!--CUROUSEL START-->
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active ">
        <img src="{% static 'images/sofa3.jpeg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/sofa4.jpg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/sofa1.jpg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
    </div>
  </div>
    <!--CUROUSEL END-->

 <!-- to make uppercase letters we use '| upper' -->
<!-- <span>WELCOME {{ name | upper }}</span> -->
<p _ngcontent-c15="" class="desc text-center text-danger"
 style="font-size: 100px; font-weight:bolder; text-shadow: 50px;">WELCOME {{name | upper}}</p>     


<br><br><br>
 <div class="row row-cols-1 row-cols-md-3 g-4">
  <!-- product:variable ,products :datas from products -->
  {% for product in products %}   
    <div class="col">
      <div class="card">
        <a href="{% url 'customer:details' product.id %}">
        <img src="{{ product.image.url }}" class="card-img-top" alt="..."></a>
        <div class="card-body">
          <h5 class="card-title">{{ product.product_name }}</h5>
          <p class="card-text">{{ product.product_description }}</p>
          <p> seller name :  {{product.seller.first_name }} {{product.seller.last_name }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    
    
  </div>


{% endblock %}

MY-PROJECT/customer/templates/customer/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/body.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     {% block link %} {% endblock %}
</head>
<body>
    
<div class="page-wraper">

        <!-- HEADER START -->
        <header class="site-header header-style-2 mobile-sider-drawer-menu" >
        
<!--NAV BAR START-->
        <header class="site-header header-style-2 mobile-sider-drawer-menu ">
            <!--Top bar section End-->
            <div class="sticky-header main-bar-wraper  navbar-expand-lg">
<nav class="navbar navbar-expand-lg " >
    <div class="container-fluid">
      <a class="navbar-brand" href="#">E FURNITURE</a>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex ms-auto" role="search">
            <input class="form-control me-0" type="search" style="border-radius: 20px; width: 400px; height: 50px;" placeholder="Search" aria-label="Search">
            <button class="btn" type="submit"><i class="bi bi-search"></i></button>
          </form>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'customer:cart' %}">
              <i class="bi bi-cart-check-fill">
            Cart</i></a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer:profile' %}"><i class="bi bi-person-check-fill">Profile</i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer:orders' %}"><i class="bi bi-bag-heart-fill">Order</i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer:logout' %}"><i class="bi bi-lock text-danger">Logout</i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer:password' %}">Change Password</a>
          </li>
        </ul>
       </div>
    </div>
  </nav>
  </div></header>
  <!--NAV BAR END-->
   






  {% block content %}
  {% endblock %}

  <!--FOOTER START-->
  <div class="card text-center bg-dark footer" >
    <div class="card-footer text-muted">
      2022 ECOM Inc,  All Rights Reserved. 
    </div>
  </div>
  <!--FOOTER END-->
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
    </html>

MY-PROJECT/customer/templates/customer/mycart.html
{% extends "customer/master.html" %}
{% load static %}
{% block link %} <link rel="stylesheet" href="{% static 'styles/mycart.css' %}"> {% endblock %}
{% block content %}
<h2 class="text-danger ms-5 mt-5">SHOPPING CART</h2>
<table>
  <thead>
    {% for item in items %}

    <tr>
      <div class="card mb-3 ms-5 mt-5" style="max-width: 840px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ item.product.image.url }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ item.product.product_name }}</h5>
              <p class="card-text"> {{ item.product.price }}</p>
              <p class="card-text">{{ item.product.product_description }} <br> Household equipment, usually made of
                wood, metal, plastics, marble, glass, fabrics, or related materials
                and having a variety of different purposes</p>
              <input type="number" id="qty{{ forloop.counter }}" data-item="{{item.product.id}}" min="1" value="1" max="{{ item.product.stock }}">Quantity
              <p>Total Price : <input type="text" value="{{item.product.price}}" class="total_amt" readonly id="amt{{item.product.id}}"></p>
              <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                <button type="submit" class="btn btn-danger">Save for later</button>

              <a href="{% url 'customer:remove_cart' item.id %}" class="btn btn-success">Remove</a>  
              </div>
            </div>
          </div>
        </div>
      </div>

    </tr>{% endfor %}
    <div class="card text-end" style="width: 18rem;">
      <div class="card-body">
        
        
        <input  id="grand_total" type="text">Total Amount :

      </div>
    </div>
    <div class="mx-auto text-center">
      <button type="submit" class="btn btn-warning ">Place order</button>
    </div>
  </thead>
</table>
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){
  display_TotalAmount()
  $.ajaxSetup({
    headers: {
      "X-CSRFToken": '{{ csrf_token }}'
    }
  })
  $('input').change(function(){
    let qty = $(this).val()
    let pid = $(this).attr('data-item')
    
    $.ajax({
      url : "{% url 'customer:total_price' %}" ,
      data : {
        'qty' : qty,
        'pid' : pid
      },
      method : 'POST',
      success :function(response){
        $('#amt' +pid).val(response.amount)
        console.log(response.amount)
        display_TotalAmount()
      }
    })
  })
})
  
function display_TotalAmount(){
 
  let amount_text = document.getElementsByClassName('total_amt')
  let total = 0
  console.log(amount_text)
  for (let i =0 ; i<amount_text.length; i++) {
    console.log('loop')
    total = total + parseInt(amount_text[i].value)
  }
  console.log(total)
  document.getElementById('grand_total').value = total
}
</script>
  {% endblock %}

MY-PROJECT/customer/templates/customer/myorders.html
{% extends "customer/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/mystyle.css' %}">
</head>
<body>
  <h2 class="head"> WELCOME</h2>
  <p id="new">Have a pleasant day</p>
  <img src="{% static 'images/flower.webp' %}">
  <a href="{% url 'customer:details' %}">details</a>
</body>
</html>

MY-PROJECT/customer/templates/customer/productdetails.html
{% extends "customer/master.html" %}
{% load static %}
{% block content %}
<div class="position-absolute top-50 start-50 translate-middle">
<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <form method = 'POST'>
            {% csrf_token %}
        <img src="{{details.image.url}}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{details.product_name}}</h5>
          <p class="card-text">{{details.product_description}}</p>
          <p class="card-text">{{details.price}}</p>
          <p class="card-text">{{details.seller.first_name}} {{details.seller.last_name}} </p>
          <button type="submit">Add to Cart</button>
          {{ message }}
        </form>
        </div>
      </div>
    </div>
    {% endblock %}

MY-PROJECT/customer/templates/customer/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>