MY-PROJECT/common/urls.py
from django.urls import path
from.import views
app_name = 'common'

urlpatterns=[
    path('admin_logo',views.admin_logo),
    path('customer_login',views.customer_login,name='clogin'),
    path('customer_signup',views.customer_signup,name='csign'),
    path('home',views.home,name='home'),
    path('seller_login',views.seller_login,name='slogin'),
    path('seller_signup',views.seller_signup,name='ssign'),
]

MY-PROJECT/ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('common/',include('common.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

MY-PROJECT/seller/urls.py
from django.urls import path
from.import views
app_name = 'seller'

urlpatterns=[
    path('add_product',views.add_product ,name='add_product'),
    path('home',views.home, name= 'home'),
    path('product_catalogue',views.product_catalogue,name='catalogue'),
    path('profile',views.profile ,name='profile'),
    path('update_stocks',views.update_stocks,name='stock'),
    path('view_order',views.view_order),
    path('master',views.master),
    path('change_password',views.change_password,name='password'),
]

MY-PROJECT/seller/models.py
from django.db import models
from common.models import Seller

# Create your models here.


class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE) 
    product_name = models.CharField(max_length=30)
    category = models.CharField(max_length=20)
    product_no= models.BigIntegerField()
    product_description = models.CharField(max_length=60)
    price = models.IntegerField(default=0)
    stock = models.IntegerField()
    image = models.ImageField(upload_to= 'product/')
    class Meta:
        db_table = 'product_tb'

MY-PROJECT/seller/views.py
from django.shortcuts import render
from common.models import Seller
from .models import Product

# Create your views here.


def add_product(request):
    if request.method  == "POST":
        category = request.POST['category']
        product_name = request.POST['product_name']
        product_no = request.POST['product_no']
        product_description = request.POST['product_description']
        price = request.POST['price']
        stock = request.POST['stock']
        image = request.FILES['image']
        seller = request.session['seller']
        new_product = Product(category = category,product_name = product_name,product_no = product_no ,

        product_description = product_description, price = price,stock = stock, image = image, seller_id=seller) 
        # seller_id   (when we set a foriegn key it comes with  _id in database)
        new_product.save() 

    return render(request,'seller/add product.html')

def home(request):
    seller_details = Seller.objects.get(id = request.session['seller'])
    products = Product.objects.filter(seller_id = request.session['seller'])
    sname = seller_details.first_name + ' ' + seller_details.last_name
    context = {
        'seller':seller_details,   
        'products' :products,
        'name' : sname 
         }
    
    return render(request,'seller/home.html',context)
     

def product_catalogue(request):
    return render(request,'seller/product catalogue.html') 

def master(request):
    return render(request,'seller/master.html')   

def profile(request):
    return render(request,'seller/profile.html')

def update_stocks(request):
    return render(request,'seller/update stocks.html')  

def view_order(request):
    return render(request,'seller/view order.html')  

def change_password(request):
    error_msg = ''
    success_msg = ''
    if request.method  == "POST":
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        if new_password == confirm_password:
            if len(new_password) > 8:
                seller = Seller.objects.get(id = request.session['seller'])
                if old_password == seller.password:
                    seller.password = new_password
                    seller.save()
                    success_msg = 'updated successfully'
                else:
                    error_msg = 'Invalid password'    

            else:
                error_msg = 'Password should be minimum 8 characters'
        
        else :
            error_msg = 'password does\'nt  match'
    

    return render(request,'seller/change password.html',{'error':error_msg,'success':success_msg})

MY-PROJECT/seller/templates/seller/add product.html
{% extends "seller/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/body1.css' %}">
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
     <style> 
     .navbar{
      position: fixed;
     }

     
    </style>
     
</head>
<body class="body2">
  


      <div  class="position-absolute top-100 start-50 translate-middle formwidth">
        <div class="modal-header">
          
            <h1 class="modal-title fs-7 mb-3 text-danger" id="exampleModalToggleLabel">Add Product</h1>
            
          </div>
      
    
<form method="POST" enctype="multipart/form-data" class="formwidth1">
          {% csrf_token %}
        <div class="row mb-3">
          <label for="inputEmail3" name="category" class="col-sm-2 col-form-label text-danger">Category Name</label>
          <div class="col-sm-8">
            <select id="fur" name="category">
                <option value="volvo">Items</option>
                <option value="volvo">Sofa</option>
                <option value="saab">Table</option>
                <option value="fiat">Chair</option>
                <option value="audi">Decor</option>
            </select>
          </div>
        </div>
        <div class="row mb-3">
          <label for="inputPassword3"  class="col-sm-2 col-form-label text-danger">Product Name</label>
          <div class="col-sm-8">
            <input type="text" name="product_name" class="form-control" id="inputPassword3">
          </div>
        </div>
        <div class="row mb-3">
            <label for="inputPassword3" class="col-sm-2 col-form-label text-danger">Product Number</label>
            <div class="col-sm-8">
              <input type="text" name="product_no"  class="form-control" id="inputPassword3">
            </div>
          </div> <div class="row mb-3">
            <label for="inputPassword3"  class="col-sm-2 col-form-label text-danger">Product Description</label>
            <div class="col-sm-8">
                <textarea class="form-control" name="product_description" id="exampleFormControlTextarea1" rows="3"></textarea>
              <!-- <input type="message" class="form-control" id="inputPassword3"> -->
            </div>
          </div> <div class="row mb-3">
            <label for="inputPassword3"  class="col-sm-2 col-form-label text-danger">Product Price</label>
            <div class="col-sm-8">
              <input type="text" class="form-control"name="price" id="inputPassword3">
            </div>
          </div>
           <div class="row mb-3">
          <label for="inputPassword3"   class="col-sm-2 col-form-label text-danger">Available stock</label>
          <div class="col-sm-8">
            <input type="text"name="stock" class="form-control" id="inputPassword3">
          </div>
        </div>
        <div class="row mb-4">
            <label for="inputPassword3"  class="col-sm-2 col-form-label text-danger">Upload Image</label>
            <div class="col-sm-8">
              <input type="file" name="image" class="form-control text-dark" id="inputPassword3" placeholder="Choose file">
            </div>
          </div>
          <button type="submit" class="btn btn-danger ">Add Product</button>
        </form>
  </div>
</div>
</div>


  <!--FOOTER START-->
  <!-- <div class="card text-center bg-dark">
    <div class="card-footer text-muted">
      2022 ECOM Inc,  All Rights Reserved. 
    </div>
  </div> -->
  <!--FOOTER END-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>
</html>
{% endblock %}

MY-PROJECT/seller/templates/seller/change password.html
{% extends "seller/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link rel="stylesheet" href="{% static 'styles/body1.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="body1">
   
    <div  class="position-absolute top-50 start-50 translate-middle form">
        <div class="modal-header">
          
            <h1 class="modal-title fs-7 mb-3 text-danger" id="exampleModalToggleLabel">Change Password</h1>
            
          </div>
    
      <form method="POST"  class="form1">
        {% csrf_token %}
        
        <div class="mb-3 ">
          <label for="exampleInputPassword1" class="form-label">Old Password</label>
          <input type="password" class="form-control" name="old_password" id="exampleInputPassword1">
        </div>
        <div class="mb-3 ">
            <label for="exampleInputPassword1" class="form-label">New Password</label>
            <input type="password" class="form-control" name="new_password" id="exampleInputPassword1">
          </div>
          <div class="mb-3 ">
            <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" name="confirm_password" id="exampleInputPassword1">
          </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
        {{success}} {{error}}
      </form>
    </div>
</div>


  <!--FOOTER START-->
  <!-- <div class="card text-center bg-dark">
    <div class="card-footer text-muted">
      2022 ECOM Inc,  All Rights Reserved. 
    </div>
  </div> -->
  <!--FOOTER END-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>
</html>
{% endblock %}

MY-PROJECT/seller/templates/seller/home.html
{% extends "seller/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/body1.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="body1">


  <!--CUROUSEL START-->
  <!-- <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active ">
        <img src="{% static 'images/sofa3.jpeg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/sofa4.jpg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/sofa1.jpg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
    </div>
  </div> -->
    <!--CUROUSEL END-->



 
<!-- <span> WELCOME  {{ name}}</span><br><br> -->

<div _ngcontent-c15="">
  
  <p _ngcontent-c15="" class="desc"style="font-size: 30px;">Welcome {{name}}</p>
</div>
<img src="{{ seller.seller_pic.url }}" height = "100px" width="200px">

<br><br><br>
 <div class="row row-cols-1 row-cols-md-3 g-4">
  {% for product in products %}
    <div class="col">
      <div class="card">
        <img src="{{ product.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ product.product_name }}</h5>
          <p class="card-text">{{ product.product_description }}</p>
          <h3 class="card-text">{{ product.price }}</h3>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
 
  <!--FOOTER START-->
  <div class="card text-center bg-dark">
    <div class="card-footer text-muted">
      2022 ECOM Inc,  All Rights Reserved. 
    </div>
  </div>
  <!--FOOTER END-->
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
  </body>
  </html>
  {% endblock %}

MY-PROJECT/seller/templates/seller/master.html
{% load static %}

    <div class="body1">
    <!--NAV BAR START-->
<nav class="navbar navbar-expand-lg nav1 sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand text-success fs-10 " style="font-family: Georgia, 'Times New Roman', Times, serif;" href="#"><i class="fa-sharp fa-solid fa-couch"></i>E-FURNITURE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex ms-auto" role="search">
            <input class="form-control me-0" type="search" style="border-radius: 20px; width: 400px; height: 50px;" placeholder="Search" aria-label="Search">
            <button class="btn" type="submit"><i class="bi bi-search"></i></button>
          </form>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'seller:home' %}"><i class="bi bi-house-fill"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'seller:add_product' %}">
           <i class="bi bi-plus-square-fill text-dark"></i>Add product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'seller:stock' %}">
           <i class="bi bi-plus-square-fill text-dark"></i>Update Stock</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'seller:password' %}">
             <i class="bi bi-c-circle text-success"></i>Change Password </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'seller:catalogue' %}">
            <i class="bi bi-c-circle-fill text-success"></i>Catalogue </a>
          </li>
          <li class="nav-item">
             <a class="nav-link" href="{% url 'seller:profile' %}"> 
         <i class="bi bi-person-plus-fill text-success"></i>Profile </a>
          </li>
        </ul>
       </div>
    </div>
  </nav>
  </div>
  <!--NAV BAR END-->


  {% block content %}
  {% endblock %}


  
 

MY-PROJECT/seller/templates/seller/profile.html
{% extends "seller/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/body1.css' %}">
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>

<body class="body2">
    <div class=" position-absolute top-50 start-0">

        <div class="header">

            <h1 class="modal-title fs-7 mb-3 text-warning" id="exampleModalToggleLabel">Personal Details</h1>

        </div>

        <form>
            <div class="row g-3">
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label text-success">First Name</label>
                    <input type="text" class="form-control" id="inputEmail4">
                </div>
                <div class="col-md-6">
                    <label for="inputPassword4" class="form-label text-success">Last Name</label>
                    <input type="text" class="form-control" id="inputPassword4">
                </div></div>
                <div class="row g-3">
                    <div class="col-12">
                        <label for="inputAddress" class="form-label text-success">Email</label>
                        <input type="email" class="form-control" id="inputAddress">
                    </div>
                </div>
                <div class="row g-3">
                <div class="col-12">
                    <label for="inputAddress2" class="form-label text-success">Phone</label>
                    <input type="phone" class="form-control" id="inputAddress2">
                </div>
            </div>
            <div class="row g-3">
                <div class="col-md-12">
                    <label for="inputCity" class="form-label text-success">Message</label>
                    <input type="text" class="form-control" id="inputCity">
                </div>
            </div>

        </form>
    </div>
    </div>


    <!-- <div class="position-relative"> -->
    <div class="position-absolute bottom-0 start-50">
        <!-- <div class=" card text-center ms-auto"> -->
        <div class="header">

            <h1 class="modal-title fs-7 mb-3 text-warning" id="exampleModalToggleLabel">Shipping Address</h1>

        </div>

        <form>
            <div class="row g-3">
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label text-success">First Name</label>
                    <input type="text" class="form-control" id="inputEmail4">
                </div>

                <div class="col-md-6">
                    <label for="inputPassword4" class="form-label text-success">Last Name</label>
                    <input type="text" class="form-control" id="inputPassword4">
                </div>
            </div>
            <div class="row g-3">
                <div class="col-12">
                    <label for="inputAddress" class="form-label text-success">Address</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
                </div>
            </div>
            <div class="row g-3">
                <div class="col-12">
                    <label for="inputAddress2" class="form-label text-success">Address 2</label>
                    <input type="text" class="form-control" id="inputAddress2"
                        placeholder="Apartment, studio, or floor">
                </div>
            </div>
            <div class="row g-3">
                <div class="col-md-12">
                    <label for="inputCity" class="form-label text-success">City</label>
                    <input type="text" class="form-control" id="inputCity">
                </div>
            </div>
            <div class="row g-3">
                <div class="col-md-12">
                    <label for="inputState" class="form-label text-success">State</label>
                    <select id="inputState" class="form-select">
                        <option selected>Choose...</option>
                        <option>Kerala</option>
                        <option>Karnataka</option>
                        <option>Tamil Nadu</option>
                        <option>Goa</option>
                    </select>
                </div>
            </div>
            <div class="row g-3">
                <div class="col-md-12">
                    <label for="inputZip" class="form-label text-success">Zip</label>
                    <input type="text" class="form-control" id="inputZip">
                </div>
            </div>
            <div class="row g-3">
                <div class="col-12">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck">
                        <label class="form-check-label" for="gridCheck">
                            Check me out
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>

    </div>
    
      <!--FOOTER START-->
  <!-- <div class="card text-center bg-dark">
    <div class="card-footer text-muted">
      2022 ECOM Inc,  All Rights Reserved. 
    </div>
  </div> -->
  <!--FOOTER END-->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>

</body>

</html>
{% endblock %}

MY-PROJECT/seller/templates/seller/update stocks.html
{% extends "seller/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/body1.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
        
          <h1 class="modal-title fs-7 mb-3 text-danger" id="exampleModalToggleLabel">Update Stock</h1>
          
        </div>
    
  
<form method="POST" class="formwidth1">
        {% csrf_token %}
      <div class="row mb-3">
        <label for="inputEmail3" name="category" class="col-sm-2 col-form-label text-danger">select product no</label>
        <div class="col-sm-8">
          <select id="fur" name="category">
              <option value="volvo">Items</option>
              <option value="volvo">Sofa</option>
              <option value="saab">Table</option>
              <option value="fiat">Chair</option>
              <option value="audi">Decor</option>
          </select>
        </div>
      </div>
      <div class="row mb-3">
        <label for="inputPassword3"  class="col-sm-2 col-form-label text-danger">Product Name</label>
        <div class="col-sm-8">
          <input type="text" name="product_name" class="form-control" id="inputPassword3">
        </div>
      </div>
      <div class="row mb-3">
          <label for="inputPassword3" class="col-sm-2 col-form-label text-danger">Current Stock</label>
          <div class="col-sm-8">
            <input type="text" name="product_no"  class="form-control" id="inputPassword3">
          </div>
        </div>
         <div class="row mb-3">
          <label for="inputPassword3"  class="col-sm-2 col-form-label text-danger">New Stock</label>
          <div class="col-sm-8">
              <textarea class="form-control" name="product_description" id="exampleFormControlTextarea1" rows="3"></textarea>
            <!-- <input type="message" class="form-control" id="inputPassword3"> -->
          </div>
        </div>
        
       
     
        <button type="submit" class="btn btn-danger ">Add Product</button>
      </form>
</div>
</div>
</div>


<!--FOOTER START-->
<!-- <div class="card text-center bg-dark">
  <div class="card-footer text-muted">
    2022 ECOM Inc,  All Rights Reserved. 
  </div>
</div> -->
<!--FOOTER END-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>


    
</body>
</html>
{% endblock %}