MY-PROJECT/common/urls.py
from django.urls import path
from.import views
app_name = 'common'

urlpatterns=[
    path('admin_logo',views.admin_logo),
    path('customer_login',views.customer_login,name='clogin'),
    path('customer_signup',views.customer_signup,name='csign'),
    path('home',views.home,name='home'),
    path('seller_login',views.seller_login,name='slogin'),
    path('seller_signup',views.seller_signup,name='ssign'),
]

MY-PROJECT/ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('common/',include('common.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

MY-PROJECT/common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email= models.CharField(max_length=50)
    password = models.CharField(max_length=20)
    phone =models.BigIntegerField()
    address = models.CharField(max_length=60)   #default = ''  if we add new field add this
 
    class Meta:
        db_table = 'customer_tb'

class Seller(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email= models.CharField(max_length=50)
    password = models.CharField(max_length=20)
    user_name =  models.IntegerField(default=0)
    phone =models.BigIntegerField()
    address = models.CharField(max_length=60)
    bank_name = models.CharField(max_length=20)
    branch = models.CharField(max_length=20)
    ifsc = models.CharField(max_length=10)
    account_no = models.CharField(max_length=15)
    seller_pic = models.ImageField(upload_to= 'seller/')
    class Meta:
        db_table = 'seller_tb'

MY-PROJECT/common/views.py
from django.shortcuts import render , redirect
from .models import Customer
from .models import Seller
from random import randint
from django.conf import settings
from django.core.mail import send_mail
# Create your views here.

def admin_logo(request):
     return render(request,'common/admin logo.html')

def customer_login(request):
    msg = ''
    if request.method  == "POST":
        email = request.POST['email']
        password = request.POST['password']
        try: 
            customer = Customer.objects.get(email = email, password = password)   #model_name= post_name
            request.session['customer'] = customer.id     # to add session
            return redirect('customer:home') #redirect(app_name:url_name)
        except Exception as e:
            print (e)   #to check error
            msg = 'Invalid credentials'

    return render(request,'common/customer login.html',{'message':msg})
    

def customer_signup(request):
    if request.method  == "POST":
        fname = request.POST['f_name']
        lname = request.POST['l_name']
        address = request.POST['address']
        phone = request.POST['phone']
        email = request.POST['email']
        password = request.POST['password']
        new_customer = Customer(first_name = fname,last_name = lname , 
        email = email,password = password, address = address, phone = phone)
        new_customer.save()  #corresponding query of insert
    return render(request,'common/customer signup.html')

def home(request):
    return render(request,'common/home.html') 

def seller_login(request):
    msg = ''
    if request.method  == "POST":
        seller_id = request.POST['seller_id']
        password = request.POST['password']
        try: 
            seller = Seller.objects.get(user_name = seller_id, password = password)
            request.session['seller'] = seller.id  
            return redirect('seller:home') #redirect(app_name:url_name)
        except:
            msg = 'Invalid credentials'

    return render(request,'common/seller login.html',{'message':msg})


def seller_signup(request):
    msg = ''
    if request.method  == "POST":
        fname = request.POST['f_name']
        lname = request.POST['l_name']
        address = request.POST['address']
        phone = request.POST['phone']
        email = request.POST['email']
        bank_name = request.POST['bank']
        branch = request.POST['branch']
        ifsc = request.POST['ifsc']
        account = request.POST['account']
        seller_pic = request.FILES['seller_pic']
        user_name = randint(1111,9999)
        password = 'sell-' + str(user_name) + '-' + phone[6:10]
    
        new_seller = Seller(first_name = fname,last_name = lname , 
        email = email,password = password, address = address, phone = phone,user_name = user_name,
        bank_name = bank_name, branch = branch,ifsc = ifsc,account_no = account,seller_pic =seller_pic)
        new_seller.save()
        msg = 'Account created successfully'
        email_subject = 'Account username and password'
        email_content = 'Hai your username will be  ' + str(user_name) + 'and password will be' + password

        send_mail(
            email_subject,
            email_content,
            settings.EMAIL_HOST_USER,
            [email,]
        )
    return render(request,'common/seller signup.html',{'message': msg})                 

MY-PROJECT/common/templates/common/admin logo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <H1>Login</H1>
</body>
</html>

MY-PROJECT/common/templates/common/customer login.html
{% extends "common/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link rel="stylesheet" href="{% static 'styles/body.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="body1">
    <div class="position-absolute top-50 start-50">
        <div class="sidebar2">
    </div>
    <div  class="position-absolute top-50 start-50 translate-middle form">
        <div class="modal-header">
          
            <h1 class="modal-title fs-7 mb-3 text-danger" id="exampleModalToggleLabel">Customer Login</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="POST"  class="form1">
            {% csrf_token %}
        <div class="mb-3 ">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" class="form-control " name="email" id="exampleInputEmail1" aria-describedby="emailHelp">
          
        </div>
        <div class="mb-3 ">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>
       
        <button type="submit" class="btn btn-primary">Submit</button>
        {{ message }}
      </form>
    </div>
</div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>
</html>
{% endblock %}

MY-PROJECT/common/templates/common/customer signup.html
{% extends "common/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link rel="stylesheet" href="{% static 'styles/body.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="body2">
  <div class=" position-absolute top-50 start-50">
    <div class="sidebar1">
  </div>
  
    <div class= "position-absolute top-50 start-50 translate-middle">
      <!-- <div class=" card text-center ms-auto"> -->
        <div class="header formwidth">
          
            <h1 class="modal-title fs-7 mb-3 text-warning" id="exampleModalToggleLabel">Customer Sign Up</h1>
           
          </div>
    <form method="POST">
        {% csrf_token %}
        <div class="col mb-2">
          <input type="text" class="form-control form-control-sm" placeholder="First name" aria-label="First name" style="width: 60%;" name='f_name';>
        </div>
        <div class="col mb-2">
          <input type="text" class="form-control form-control-sm" placeholder="Last name" name="l_name" aria-label="Last name" style="width: 60%;">
        </div>
      
      <div class="col mb-2">
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Address" name="address" style="width: 60%;"></textarea>
        </div>
      <div class="col mb-2">
        <input type="tel" class="form-control form-control-sm" placeholder="Phonenumber" aria-label="First name" name="phone" style="width: 60%;">
      </div>
      <div class="col mb-2">
        <input type="email" class="form-control form-control-sm" placeholder="Email" aria-label="First name" name="email" style="width: 60%;">
      </div>
      <div class="col mb-2">
        <input type="password" class="form-control form-control-sm" placeholder="Password" aria-label="First name" name="password" style="width: 60%;">
      </div>
      <div class="col mb-2">
        <button type="submit" class="btn btn-outline-warning" style="width: 25%;">Sign up</button>
      </div>
    </div>
    <!-- <div class="mb- form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-outline-success" style="width: 25%;">Login</button> -->
    <div class="modal-footer justify-content-center">
      
      <span>Already have an account?</span><button class="btn btn-link text-success" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Login Here</button>
    </div>
  </div>
</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>
</html>
{% endblock %}

MY-PROJECT/common/templates/common/home.html
{% extends "common/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link rel="stylesheet" href="{% static 'styles/body.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

  <!--CUROUSEL START-->
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active ">
        <img src="{% static 'images/sofa3.jpeg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/sofa4.jpg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/sofa1.jpg' %}" class="d-block w-100 imgsize " alt="...">
      </div>
    </div>
  </div>
    <!--CUROUSEL END-->

<br><br><br>
 <div class="row row-cols-1 row-cols-md-3 g-4">
  <!-- product:variable products :datas from Product model -->
 
    <div class="col">
      <div class="card">
        <img src="{% static 'images/m11.avif' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">NAME</h5>
          <p class="card-text">DESCRIPTION</p>
         
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <img src="{% static 'images/m12.webp' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">NAME</h5>
          <p class="card-text">DESCRIPTION</p>
         
        </div>
      </div>
    </div>
    
    
    
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body</html>


{% endblock %}

MY-PROJECT/common/templates/common/master.html
{% load static %}
<!--NAV BAR START-->
<nav class="navbar navbar-expand-lg nav1 fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand text-success fs-10 " style="font-family: Georgia, 'Times New Roman', Times, serif;" href="#"><i class="fa-sharp fa-solid fa-couch"></i>E-FURNITURE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex ms-auto" role="search">
            <input class="form-control me-0" type="search" style="border-radius: 20px; width: 400px; height: 50px;" placeholder="Search" aria-label="Search">
            <button class="btn" type="submit"><i class="bi bi-search"></i></button>
          </form>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'common:home' %}"><i class="bi bi-house-fill"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'common:clogin' %}">
            <i class="bi bi-person-square text-danger"></i>Customer Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'common:csign' %}">
          <i class="bi bi-person-square text-danger"></i>Customer Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'common:slogin' %}">
         <i class="bi bi-person-plus-fill text-success"></i>Seller Login </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'common:ssign' %}">
          <i class="bi bi-person-square text-danger"></i>Seller Register</a>
          </li>
        </ul>
       </div>
    </div>
  </nav>
  <!--NAV BAR END-->

{% block content %}
{% endblock %}


  <!--FOOTER START-->
  <div class="card text-center bg-dark">
    <div class="card-footer text-muted">
      2022 ECOM Inc,  All Rights Reserved. 
    </div>
  </div>
  <!--FOOTER END-->

MY-PROJECT/common/templates/common/seller login.html
{% extends "common/master.html" %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link rel="stylesheet" href="{% static 'styles/body.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="body1">
  <div class="position-absolute top-50 start-50">
      <div class="sidebar2">
  </div>
  <div  class="position-absolute top-50 start-50 translate-middle form">
      <!-- <div class=" col align-self-center"> -->
        <div class="modal-header  ">
          
            <h1 class="modal-title fs-7 mb-3 text-success" id="exampleModalToggleLabel">Seller Login</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="POST"  class="form1">
            {% csrf_token %}
        <div class="mb-3 col align-self-center ">
          <label for="exampleInputEmail1" class="form-label">Seller ID</label>
          <input type="text" class="form-control " name="seller_id" id="exampleInputEmail1" aria-describedby="emailHelp">
         
        </div>
        <div class="mb-3 ">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" name="password" id="exampleInputPassword1">
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
        {{ message }}
      </form>
    </div>
</div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>
</html>
{% endblock %}

MY-PROJECT/common/templates/common/seller signup.html
{% extends "common/master.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-FURNITURE</title>
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
    <link rel="stylesheet" href="{% static 'styles/body.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="body2"> 
  <div class=" position-absolute top-100 start-50">
  <div class="sidebar1">
</div>

  <div class= "position-absolute top-50 start-50 translate-middle">
    <!-- <div class=" card text-center ms-auto"> -->
      <div class="header formwidth">
        
          <h1 class="modal-title fs-7 mb-3 text-secondary" id="exampleModalToggleLabel">Seller Sign Up</h1>
         
        </div>
    <form method="POST" enctype="multipart/form-data" class="form2">
        {% csrf_token %}
        <div class="col mb-2">
          <input type="text" class="form-control form-control-sm" placeholder="First name" aria-label="First name" style="width: 60%;" name='f_name';>
        </div>
        <div class="col mb-2">
          <input type="text" class="form-control form-control-sm" placeholder="Last name" name="l_name" aria-label="Last name" style="width: 60%;">
        </div>
      
      <div class="col mb-2">
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Address" name="address" style="width: 60%;"></textarea>
        </div>
      <div class="col mb-2">
        <input type="tel" class="form-control form-control-sm" placeholder="Phonenumber" aria-label="First name" name="phone" style="width: 60%;">
      </div>
    
      <div class="col mb-2">
        <input type="email" class="form-control form-control-sm" placeholder="Email" aria-label="First name" name="email" style="width: 60%;">
      </div>
      
      <div class="col mb-2">
        <input type="text" class="form-control form-control-sm" placeholder="Bank name" aria-label="First name" name="bank" style="width: 60%;">
      </div>
      <div class="col mb-2">
        <input type="text" class="form-control form-control-sm" placeholder="Bank Branch" aria-label="First name" name="branch" style="width: 60%;">
      </div>
        <div class="col mb-2">
            <input type="text" class="form-control form-control-sm" placeholder="IFSC" aria-label="First name" name="ifsc" style="width: 60%;">
          </div>
        <div class="col mb-2">
            <input type="text" class="form-control form-control-sm" placeholder="Account Number" aria-label="First name" name="account" style="width: 60%;">
          </div>  
          <div class="col mb-2">
            <input type="file" class="form-control form-control-sm" placeholder="choose image" aria-label="First name" name="seller_pic" style="width: 60%;">
          </div> 
      <div class="col mb-2">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label text-danger" for="exampleCheck1">Check me out</label>
      </div>
      <div class="col mb-2">
        <button type="submit" class="btn btn-outline-secondary" style="width: 25%;">Sign up</button>
      </div>
    </div><br>
    {{ message }}
    <!-- <div class="mb- form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-outline-success" style="width: 25%;">Login</button> -->
    <!-- <div class="modal-footer justify-content-center">
      
      <span>Already have an account?</span><button class="btn btn-link text-success" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Login Here</button>
    </div> -->
  </div>
</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
</body>
</html>
{% endblock %}